In [8]:
!pip install librosa soundfile numpy scikit-learn matplotlib tensorflow


In [9]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [10]:
!ls /content/drive/MyDrive/

 02fd4a0e-28de-4dd5-a802-95d8a0e840db.jpeg  'q3 (1).ipynb'
 Classroom				    'q3 (2).ipynb'
'Colab Notebooks'			     q3.ipynb
 emotion_model.pkl			     Resume.gdoc
 filimstarts				    'Scan 29 Jan 22 · 13·46·33.pdf'
'full AI'				    'speech emotion'
'Getting started.pdf'			     theoritykal.gdoc
'image (1).jpg'				    'Ttr rsumd.pdf'
 image.jpg				    'Untitled document.gdoc'
 IMG_20210722_215128_795.jpg		    'Untitled form (1).gform'
 IMG-20240207-WA0037.jpg		    'Untitled form.gform'
'import numpy as np.gdoc'		    'Untitled spreadsheet (1).gsheet'
 Jinu13_07_2024.pdf			    'Untitled spreadsheet (2).gsheet'
 label_encoder.pkl			    'Untitled spreadsheet.gsheet'


In [11]:
import pathlib
import cv2

In [12]:
pic_path=pathlib.Path('/content/drive/MyDrive/speech emotion')

In [13]:
import numpy as np
import librosa
import soundfile as sf
from pathlib import Path

# Your dataset path as a Path object
pic_path = Path('/content/drive/MyDrive/speech emotion')

# Emotion mapping from RAVDESS filename
emotion_map = {
    '01': 'neutral',
    '02': 'calm',
    '03': 'happy',
    '04': 'sad',
    '05': 'angry',
    '06': 'fearful',
    '07': 'disgust',
    '08': 'surprised'
}

def extract_features(file_path):
    try:
        audio, sample_rate = sf.read(file_path)
        if len(audio.shape) > 1:  # Convert stereo to mono if needed
            audio = np.mean(audio, axis=1)
        mfccs = librosa.feature.mfcc(y=audio.astype(float), sr=sample_rate, n_mfcc=40)
        mfccs_processed = np.mean(mfccs.T, axis=0)
        return mfccs_processed
    except Exception as e:
        print(f"❌ Error encountered while parsing file: {file_path}\n{e}")
        return None

features = []

# Loop through all .wav files recursively using pathlib
for wav_file in pic_path.rglob('*.wav'):
    data = extract_features(wav_file)
    if data is not None:
        emotion_code = wav_file.name.split('-')[2]
        emotion = emotion_map.get(emotion_code)
        if emotion:
            features.append([data, emotion])

print(f"\n✅ Successfully extracted features from {len(features)} files.")



✅ Successfully extracted features from 120 files.


In [14]:
import pandas as pd
df = pd.DataFrame(features, columns=['feature', 'emotion'])
df

,feature,emotion
0,"[-708.9373160221807, 70.3367413883307, 9.48916...",calm
1,"[-654.7452557947745, 77.33869534265605, 1.8005...",neutral
2,"[-647.6288594682513, 70.0531812008131, -2.6148...",neutral
3,"[-677.0451738938576, 79.10089456138586, 1.4322...",neutral
4,"[-645.6034032644797, 73.7788741805912, 2.40223...",neutral
...,...,...
115,"[-536.6904272176128, 43.285824585581366, -9.27...",surprised
116,"[-481.2887894305634, 26.91709890269966, -27.85...",fearful
117,"[-594.1310515537137, 69.70294755979504, -12.52...",disgust
118,"[-591.2937767372897, 49.85480633460077, -14.40...",surprised


In [15]:
X = np.array(df['feature'].tolist())
y = np.array(df['emotion'].tolist())


In [16]:
X

array([[-7.08937316e+02,  7.03367414e+01,  9.48916182e+00, ...,
        -1.98630787e+00, -1.00778545e+00, -1.55282435e+00],
       [-6.54745256e+02,  7.73386953e+01,  1.80054785e+00, ...,
        -1.74693605e+00, -1.91372549e+00, -1.71538590e+00],
       [-6.47628859e+02,  7.00531812e+01, -2.61489959e+00, ...,
        -3.13011922e+00, -3.21811952e+00, -2.88732302e+00],
       ...,
       [-5.94131052e+02,  6.97029476e+01, -1.25258678e+01, ...,
         2.06864491e+00,  7.89693883e-01,  3.09036523e+00],
       [-5.91293777e+02,  4.98548063e+01, -1.44076492e+01, ...,
         8.93311434e-01,  1.21592060e+00,  2.28581738e+00],
       [-4.64866134e+02,  2.65943422e+01, -2.95428791e+01, ...,
        -1.26388136e+00, -3.52388102e-01,  3.41325574e+00]])

In [17]:
X[1]

array([-6.54745256e+02,  7.73386953e+01,  1.80054785e+00,  6.38117726e+00,
        6.23091226e+00,  2.02782130e+01, -8.47550044e+00,  3.12945644e+00,
        4.22287977e-01, -1.65878262e+00, -5.96241438e+00, -3.03953452e+00,
        2.84672659e+00, -3.79163479e-01, -2.72113904e+00,  1.52525254e+00,
       -6.99200861e-01, -2.90243671e+00,  1.55909089e+00, -1.47691028e-01,
       -2.93646579e+00, -2.21668272e+00, -8.99664324e-01, -6.41414921e-01,
       -2.67780354e+00, -1.24883770e+00, -1.06370618e+00, -2.60739595e+00,
       -1.29274795e+00, -1.81442307e+00, -1.57068026e+00, -2.46232806e-01,
       -2.08109826e+00, -1.48288602e+00, -4.58899170e-01, -1.51416592e+00,
       -1.74877518e+00, -1.74693605e+00, -1.91372549e+00, -1.71538590e+00])

In [18]:
y

array(['calm', 'neutral', 'neutral', 'neutral', 'neutral', 'fearful',
       'happy', 'happy', 'happy', 'disgust', 'sad', 'angry', 'calm',
       'neutral', 'happy', 'disgust', 'happy', 'fearful', 'happy',
       'angry', 'sad', 'calm', 'calm', 'happy', 'angry', 'calm', 'calm',
       'sad', 'angry', 'happy', 'calm', 'disgust', 'disgust', 'disgust',
       'angry', 'happy', 'angry', 'sad', 'happy', 'sad', 'disgust',
       'calm', 'surprised', 'angry', 'neutral', 'sad', 'calm',
       'surprised', 'fearful', 'angry', 'fearful', 'angry', 'calm',
       'calm', 'angry', 'sad', 'happy', 'disgust', 'sad', 'happy', 'sad',
       'sad', 'sad', 'angry', 'angry', 'sad', 'surprised', 'happy',
       'calm', 'sad', 'fearful', 'calm', 'surprised', 'angry', 'fearful',
       'surprised', 'sad', 'angry', 'happy', 'angry', 'surprised', 'calm',
       'fearful', 'angry', 'sad', 'fearful', 'disgust', 'surprised',
       'calm', 'happy', 'neutral', 'calm', 'sad', 'happy', 'surprised',
       'neutral',

In [19]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)


In [21]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
model = MLPClassifier(hidden_layer_sizes=(256, 128, 64), activation='relu', solver='adam', max_iter=500)
model.fit(X_train, y_train)



/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(256, 128, 64), max_iter=500)

In [22]:
y_pred = model.predict([[-6.54745256e+02,  7.73386953e+01,  1.80054785e+00,  6.38117726e+00,
        6.23091226e+00,  2.02782130e+01, -8.47550044e+00,  3.12945644e+00,
        4.22287977e-01, -1.65878262e+00, -5.96241438e+00, -3.03953452e+00,
        2.84672659e+00, -3.79163479e-01, -2.72113904e+00,  1.52525254e+00,
       -6.99200861e-01, -2.90243671e+00,  1.55909089e+00, -1.47691028e-01,
       -2.93646579e+00, -2.21668272e+00, -8.99664324e-01, -6.41414921e-01,
       -2.67780354e+00, -1.24883770e+00, -1.06370618e+00, -2.60739595e+00,
       -1.29274795e+00, -1.81442307e+00, -1.57068026e+00, -2.46232806e-01,
       -2.08109826e+00, -1.48288602e+00, -4.58899170e-01, -1.51416592e+00,
       -1.74877518e+00, -1.74693605e+00, -1.91372549e+00, -1.71538590e+00]])
y_pred

array([5])

In [23]:
y_pred = model.predict(X_test)
y_pred


array([5, 4, 5, 6, 1, 0, 0, 7, 2, 3, 4, 6, 0, 0, 4, 1, 2, 1, 1, 3, 6, 4,
       2, 2])

In [24]:
accuracy = accuracy_score(y_test, y_pred)
print(f"\n🎯 Model Accuracy: {accuracy * 100:.2f}%\n")
print("🧾 Classification Report:")
print(classification_report(y_test, y_pred, target_names=le.classes_))
print("📊 Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))



🎯 Model Accuracy: 83.33%

🧾 Classification Report:
              precision    recall  f1-score   support

       angry       1.00      1.00      1.00         4
        calm       1.00      1.00      1.00         4
     disgust       0.75      1.00      0.86         3
     fearful       1.00      0.67      0.80         3
       happy       0.50      1.00      0.67         2
     neutral       1.00      1.00      1.00         2
         sad       1.00      0.60      0.75         5
   surprised       0.00      0.00      0.00         1

    accuracy                           0.83        24
   macro avg       0.78      0.78      0.76        24
weighted avg       0.89      0.83      0.84        24

📊 Confusion Matrix:
[[4 0 0 0 0 0 0 0]
 [0 4 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0]
 [0 0 1 2 0 0 0 0]
 [0 0 0 0 2 0 0 0]
 [0 0 0 0 0 2 0 0]
 [0 0 0 0 1 0 3 1]
 [0 0 0 0 1 0 0 0]]


In [25]:
!pip install resampy


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 30.1 MB/s eta 0:00:00


In [26]:
from google.colab import files

# Function to predict emotion from a single audio file
def predict_emotion(file_path):
    # Extract features from the uploaded file
    features = extract_features(file_path)
    if features is not None:
        features = np.array(features).reshape(1, -1)  # Reshape for model
        prediction = model.predict(features)
        predicted_emotion = le.inverse_transform(prediction)[0]
        return predicted_emotion
    else:
        return "Could not process the audio file."

# Upload an audio file
print("📤 Please upload a .wav audio file...")
uploaded = files.upload()

# Loop through uploaded files and make predictions
for file_name in uploaded.keys():
    file_path = f"/content/{file_name}"
    emotion = predict_emotion(file_path)
    print(f"🎤 Audio File: {file_name}")
    print(f"😊 Predicted Emotion: {emotion}")


📤 Please upload a .wav audio file...


Saving 03-01-06-02-01-01-24.wav to 03-01-06-02-01-01-24 (1).wav
🎤 Audio File: 03-01-06-02-01-01-24 (1).wav
😊 Predicted Emotion: fearful


In [27]:
!git config --global user.name "jinup7"
!git config --global user.email "Jinucr7123*"